name: timedatecalculator
base: core20
version: "6.4.27"
summary: Calculates times and time spans
description: |
  timedatecalculator
  calculates time and date from start-/end time
  and time span or time span from start- and end time and date
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
# confinement: devmode # use 'strict' once you have the right plugs and slots
# grade: stable # must be 'stable' to release into candidate/stable channels
# confinement: strict # use 'strict' once you have the right plugs and slots
# confinement: devmode # use 'strict' once you have the right plugs and slots

# architectures:
#   - build-on: amd64
#   - build-on: s390x
#   - build-on: arm64
#   - build-on: armhf
#   - build-on: i386
# package-repositories:
#   - type: apt
#     formats: [deb]
#     components: [main]
#     suites: [stable-focal]
#     key-id: 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
#     url: https://download.mono-project.com/repo/ubuntu

layout:
  /usr/lib/cli/gdk-sharp-2.0:
    bind: $SNAP/usr/lib/cli/gdk-sharp-2.0
  /usr/lib/cli/gtk-sharp-2.0:
    bind: $SNAP/usr/lib/cli/gtk-sharp-2.0
  /usr/lib/cli/glib-sharp-2.0:
    bind: $SNAP/usr/lib/cli/glib-sharp-2.0
  $SNAP/usr/lib/cli/gtk-sharp-2.0/libgtk-x11-2.0.so.0:
    symlink: $SNAP/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
  $SNAP/usr/lib/cli/gtk-sharp-2.0/libgtk-x11-2.0.so.0.so:
    symlink: $SNAP/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
  $SNAP/usr/lib/cli/gtk-sharp-2.0/libMonoSupportW.so:
    symlink: $SNAP/usr/lib/libMonoSupportW.so
  $SNAP/usr/lib/cli/glib-sharp-2.0/libglib-2.0.so.0:
    symlink: $SNAP/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
  $SNAP/usr/lib/cli/glib-sharp-2.0/libgobject-2.0.so.0:
    symlink: $SNAP/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0

environment:
  MONO_CFG_DIR: $SNAP/etc
  MONO_CONFIG: $SNAP/etc/mono/config
  MONO_GAC_PREFIX: $SNAP/usr/lib/mono
  MONO_PATH: $SNAP/usr/lib/x86_64-linux-gnu:$SNAP/gnome-platform/usr/lib/x86_64-linux-gnu:$SNAP/etc/mono:$SNAP/usr/bin:$SNAP/usr/lib:$SNAP/usr/lib/mono:$SNAP/usr/share/mono:$SNAP/usr/lib/cli:$SNAP/usr/lib/cli/atk-sharp-2.0:$SNAP/usr/lib/cli/gdk-sharp-2.0:$SNAP/usr/lib/cli/gtk-sharp-2.0:$SNAP/usr/lib/cli/glib-sharp-2.0
# MONO_PATH: $SNAP/etc/mono:$SNAP/usr/bin:$SNAP/usr/lib:$SNAP/usr/lib/mono:$SNAP/usr/share/mono:$SNAP/usr/lib/cli:$SNAP/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0:$SNAP/usr/lib/x86_64-linux-gnu:$SNAP/usr/lib/cli/gtk-sharp-2.0:$SNAP/usr/lib/cli/glib-sharp-2.0:$SNAP/usr/lib/cli/atk-sharp-2.0:$SNAP/usr/lib/cli/gdk-sharp-2.0
  # MONO_LOG_LEVEL: debug
  # MONO_LOG_MASK: dll

package-repositories:
  - type: apt
    formats: [deb]
    components: [main]
    suites: [vs-bionic]
    key-id: 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
    url: https://download.mono-project.com/repo/ubuntu

parts:
  timedatecalculator:
    # after: [monoinstall]
    source: .
    plugin: nil
    # build-environment:
    #   - MONO_CFG_DIR: $SNAPCRAFT_PART_INSTALL/etc
    #   - MONO_CONFIG: $SNAPCRAFT_PART_INSTALL/etc/mono/config
    #   - MONO_GAC_PREFIX: $SNAPCRAFT_PART_INSTALL/usr/lib/mono
    #   - MONO_PATH: $SNAPCRAFT_PART_INSTALL/etc/mono:$SNAPCRAFT_PART_INSTALL/usr/bin:$SNAPCRAFT_PART_INSTALL/usr/lib:$SNAPCRAFT_PART_INSTALL/usr/lib/mono:$SNAPCRAFT_PART_INSTALL/usr/share/mono:$SNAPCRAFT_PART_INSTALL/usr/lib/cli:$SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu:$SNAPCRAFT_PART_INSTALL/usr/lib/cli/gtk-sharp-2.0:$SNAPCRAFT_PART_INSTALL/usr/lib/cli/glib-sharp-2.0
    override-build: |
      cp ./eksfind.sh $SNAPCRAFT_PART_INSTALL/
      cp ./ekstxtfind.sh $SNAPCRAFT_PART_INSTALL/
      nuget restore
      cd TimeDateCalculator/TimeDateCalculator.gtk
      msbuild -t:Rebuild -p:Configuration=debug
      cd bin/Debug
      cp -rf ./* $SNAPCRAFT_PART_INSTALL/
    build-packages:
      - curl
      - nuget
      - mono-complete
      - apt-transport-https
      - dirmngr
      - monodevelop
    stage-packages:
      - ca-certificates-mono
      # - libfreetype6
      # - libgdiplus
      # - libglu1-mesa
      # - liblttng-ust0
      # - liblua5.1-0
      # - libopenal1
      # - libsdl2-2.0-0
      # - libgtk2.0-0
      - libuser
      - libgail-common
      - libgail-3-0
      - libatk-bridge2.0-0
      - libglib2.0-0
      - mono-runtime
      - mono-runtime-sgen
      # - mono-llvm-support
      - libmono-2.0-1
      - libmono-profiler
      - mono-utils
      - mono-devel
      - mono-mcs
      # - mono-roslyn
      - mono-csharp-shell
      - mono-4.0-gac
      - mono-4.0-service
      - monodoc-base
      - monodoc-manual
      - libmono-cil-dev
      # - referenceassemblies-pcl
      # - msbuild
      - mono-complete
      - gtk-sharp2
      - libgtk2.0-cil
      - libgtk2.0-cil-dev

apps:
  timedatecalculator:
    extensions: [gnome-3-38]
    command: usr/bin/mono $SNAP/TimeDateCalculator.gtk.exe
    # adapter: none
    # plugs: 
    #   - home
    #   - x11
    #   - desktop
    #   - desktop-legacy
    #   - gsettings
    #   - opengl
